# Generated by Django 3.0.5 on 2020-04-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epidemic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityEnglishName', models.TextField()),
                ('cityName', models.TextField()),
                ('confirmedCount', models.IntegerField()),
                ('curedCount', models.IntegerField()),
                ('currentConfirmedCount', models.IntegerField()),
                ('deadCount', models.IntegerField()),
                ('locationId', models.IntegerField()),
                ('suspectedCount', models.IntegerField()),
                ('updateTime', models.CharField(max_length=20)),
            ],
        ),
    ]
