# Generated by Django 3.0.5 on 2020-05-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentanalysis', '0002_chinaconfirmedcount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChinaConfirmedCount',
            new_name='China',
        ),
    ]
