# Generated by Django 3.0.5 on 2020-04-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weibomic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField()),
                ('keyword', models.TextField()),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
