# Generated by Django 3.0.5 on 2020-04-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weiboAnalytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weibomic',
            new_name='Weibo',
        ),
    ]
