# Generated by Django 3.0.5 on 2020-04-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboAnalytics', '0002_auto_20200404_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibo',
            name='address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
