# Generated by Django 3.0.5 on 2020-04-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboAnalytics', '0003_weibo_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weibo',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='weibo',
            name='keyword',
        ),
        migrations.AddField(
            model_name='weibo',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weibo',
            name='name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weibo',
            name='source',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weibo',
            name='time',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
